#!/bin/sh -e

# set default turtlebot 3 model
snapctl set turtlebot3-model=waffle_pi

# set default ROS master hostname
snapctl set ros-master-host=$(hostname).local

if ! snapctl is-connected ros-noetic-robot; then
  logger -t ${SNAP_NAME} "Plug 'ros-noetic-robot' isn't connected, \
    please run: snap connect ${SNAP_NAME}:ros-noetic-robot <providing-snap>"
fi
