name: turtlebot3c-teleop
version: '0.1'
license: GPL-3.0
summary: Turtlebot3c teleop snap
description: |
  This snap automatically spawn a roscore and the core components for the
  Turtlebot3.

  This snap is meant to run on the Turtlebot3 robot or with the simulation

  By default the snap runs on the robot.
  To switch to the simulation

    snap set turtlebot3c-teleop simulation=true

  By default the snap used the lidar LDS-01 robot.
  To select the other lidar for the robot

    snap set turtlebot3c-teleop lds-model=LDS-02

  By default the snap runs the waffle_pi Turtlebot3 model.
  To select another robot model (waffle or burger)

    snap set turtlebot3c-teleop turtlebot3-model=burger

grade: stable
confinement: strict
base: core20 # Noetic

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  workspace:
    plugin: catkin
    source: https://github.com/ubuntu-robotics/turtlebot3c.git
    source-branch: artivis-patch-1
    source-subdir: turtlebot3c_teleop

  # copy local scripts to the snap usr/bin
  local-files:
    no_extension: True
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/

apps:
  core:
    # daemon: simple
    environment:
      ROS_HOME: $SNAP_USER_DATA/ros
      # LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
    command-chain: [usr/bin/ros_network.sh]
    command: roslaunch turtlebot3c_teleop turtlebot3c_teleop.launch
    plugs: [network, network-bind]
    extensions: [ros1-noetic-robot]

  key:
    environment:
      ROS_HOME: $SNAP_USER_DATA/ros
    command-chain: [usr/bin/ros_network.sh, usr/bin/mux_select_key_vel.sh]
    command: roslaunch turtlebot3c_teleop key.launch
    plugs: [network, network-bind]
    extensions: [ros1-noetic-robot]

  joy:
    environment:
      ROS_HOME: $SNAP_USER_DATA/ros
    command-chain: [usr/bin/ros_network.sh, usr/bin/mux_select_joy_vel.sh]
    command: roslaunch turtlebot3c_teleop joy.launch
    plugs: [network, network-bind, joystick]
    extensions: [ros1-noetic-robot]
