name: turtlebot3c-bringup
version: '0.1'
license: GPL-3.0
summary: Turtlebot3c core snap
description: |
  This snap automatically spawn a roscore and the core components for the
  Turtlebot3 (controller, robot_state_publisher etc).

  By default, the snap is configured for the 'waffle_pi' Turtlebot3 model.
  To select another robot model (waffle or burger) run the following,

    snap set turtlebot3c-bringup turtlebot3-model=burger

  Similarly, the snap is configured to consider the lidar model LDS-01.
  To select the other lidar for the robot run the following,

    snap set turtlebot3c-bringup lds-model=LDS-02

  This snap is meant to run on the Turtlebot3 robot,
  but it can also be used with the simulation.

  In order to use it with the simulation, issue the following in the terminal,

    snap set turtlebot3c-bringup simulation=true

grade: stable
confinement: strict
base: core20 # Noetic

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  workspace:
    plugin: catkin
    source: https://github.com/ubuntu-robotics/turtlebot3c.git
    source-branch: artivis-patch-1
    source-subdir: turtlebot3c_bringup

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/

apps:
  core:
    # daemon: simple
    environment:
      ROS_HOME: $SNAP_USER_DATA/ros
      # LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
    command-chain: [usr/bin/ros_network.sh]
    command: usr/bin/core_launcher.sh
    plugs: [network, network-bind, raw-usb]
    extensions: [ros1-noetic-robot]
