name: turtlebot3c-bringup
version: '0.1'
license: GPL-3.0
summary: Turtlebot3c core snap
description: |
  This snap automatically spawn a roscore and the core components for the
  Turtlebot3.

  This snap is meant to run on the Turtlebot3 robot or with the simulation

  By default the snap runs on the robot.
  To switch to the simulation

    snap set turtlebot3c simulation=true

  By default the snap used the lidar LDS-01 robot.
  To select the other lidar for the robot

    snap set turtlebot3c lds-model=LDS-02

  By default the snap runs the waffle_pi Turtlebot3 model.
  To select another robot model (waffle or burger)

    snap set turtlebot3c turtlebot3-model=burger

grade: stable
confinement: strict
base: core22 # Humble

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  turtlebot3c-bringup:
    plugin: colcon
    source: https://github.com/ROBOTIS-GIT/turtlebot3.git
    source-branch: humble-devel
    source-subdir: turtlebot3_bringup

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/

apps:
  core:
    daemon: simple
    environment:
      ROS_HOME: $SNAP_USER_DATA/ros
    command-chain: [usr/bin/ros_network.sh]
    command: usr/bin/core_launcher.sh
    plugs: [network, network-bind, raw-usb]
    extensions: [ros2-humble-ros-base]
