name: turtlebot3c-bringup
version: '0.1'
license: GPL-3.0
summary: TurtleBot3c core snap
description: |
  This snap automatically spawn a roscore and the core components for the
  TurtleBot3 (controller, robot_state_publisher etc).

  By default, the snap is configured for the 'waffle_pi' TurtleBot3 model.
  To select another robot model (waffle or burger) run the following,

    snap set turtlebot3c-bringup turtlebot3-model=burger

  Similarly, the snap is configured to consider the lidar model LDS-01.
  To select the other lidar for the robot run the following,

    snap set turtlebot3c-bringup lds-model=LDS-02

  This snap is meant to run on the TurtleBot3 robot.

grade: stable
confinement: strict
base: core24 # Jazzy

platforms:
  amd64:
  arm64:
  armhf:

parts:
  turtlebot3c-bringup:
    plugin: colcon
    source: .
    override-pull: |
      git init
      # Humble-devel compiles on jazzy. Using source packages to build bringup package
      # since those are not yet available in jazzy.
      git clone -b humble-devel https://github.com/ROBOTIS-GIT/turtlebot3.git
      cd turtlebot3 && git sparse-checkout set turtlebot3_bringup/ turtlebot3_description/ turtlebot3_node/
      craftctl default
    build-packages:
      - git

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/

apps:
  core:
    daemon: simple
    environment:
      ROS_HOME: $SNAP_USER_DATA/ros
    command-chain: [usr/bin/ros_network.sh]
    command: usr/bin/core_launcher.sh
    plugs: [network, network-bind, raw-usb]
    extensions: [ros2-jazzy-ros-base]
