#!/bin/sh -e

# set default lidar model for real robot
snapctl set lds-model=LDS-01

# set default turtlebot 3 model
snapctl set turtlebot3-model=waffle_pi

# set default ROS localhost only and ros-domain-id
snapctl set ros-localhost-only=0
snapctl set ros-domain-id=0

if ! snapctl is-connected ros-jazzy-ros-base; then
  logger -t ${SNAP_NAME} "Plug 'ros-jazzy-ros-base' isn't connected, \
    please run: snap connect ${SNAP_NAME}:ros-jazzy-ros-base <providing-snap>"
fi
