#!/bin/sh -e

# set default configuration values
snapctl set simulation=false

# set default lidar model for real robot
snapctl set lds-model=LDS-01

# set default turtlebot 3 model
snapctl set turtlebot3-model=waffle_pi

# set default ROS master hostname
snapctl set ros-master-host=$(hostname).local

if ! snapctl is-connected ros-noetic-robot; then
  logger -t ${SNAP_NAME} "Plug 'ros-noetic-robot' isn't connected, \
    please run: snap connect ${SNAP_NAME}:ros-noetic-robot <providing-snap>"
fi

# set default OpenCR firmware auto update
snapctl set opencr-auto-update=false

