name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  noetic-devel-snap:
    uses: canonical/turtlebot3c-snap/.github/workflows/snap.yaml@fix/monthly
    with:
      branch-name: "fix/monthly"
  multi-snap:
    uses: canonical/turtlebot3c-snap/.github/workflows/snap.yaml@feature/multi-snap-unique-name
    with:
      branch-name: feature/multi-snap-unique-name
  multi-snap-humble:
    uses: canonical/turtlebot3c-snap/.github/workflows/snap.yaml@feature/multi-snap-humble-unique-name
    with:
      branch-name: feature/multi-snap-humble-unique-name
  multi-snap-jazzy:
    uses: canonical/turtlebot3c-snap/.github/workflows/snap.yaml@feature/multi-snap-jazzy-unique-name
    with:
      branch-name: feature/multi-snap-jazzy-unique-name

