name: snap
on:
  push:
    branches:
      - debugging-tutorial
  pull_request:
    branches:
      - debugging-tutorial
  workflow_dispatch:
  workflow_call:
   inputs:
      branch-name:
        required: false
        type: string
        default: ''

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    with:
      runs-on: '["ubuntu-latest", "ubuntu-24.04-arm"]'
      lxd-image: "ubuntu:20.04"
      snapcraft-source-subdir: "."
      snapcraft-channel: "8.x/stable"
      git-ref: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
