name: test turtlebot multi snap

on:
  push:
    branches:
      - feature/multi-snap
  pull_request:
    branches:
      - feature/multi-snap
  workflow_dispatch:

jobs:

  # Collect all relative paths containing a 'snap/snapcraft.yaml'
  collect_dirs:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - id: dirs
        run: echo "dirs=$(find . -type f -name 'snapcraft.yaml' | sed -r 's|\/snap/[^/]+$||' |sort |uniq |jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  # Run snapcraft for each example
  run_tests:
    needs: collect_dirs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJson(needs.collect_dirs.outputs.dirs) }}
    name: "Snap ${{ matrix.dir }}"
    steps:
      - uses: actions/checkout@v3
      - uses: snapcore/action-build@v1
        id: build-snap
        with:
          # Select the example we want to build
          path: "${{ matrix.dir }}"
          snapcraft-channel: 'latest/candidate'

      # Make sure the snap is installable
      - run: sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}

      - uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: snaps
          path: ${{ steps.build-snap.outputs.snap }}
          retention-days: 7
