name: test turtlebot multi snap

on:
  push:
    branches:
      - feature/multi-snap
  pull_request:
    branches:
      - feature/multi-snap
  workflow_dispatch:
  workflow_call:

jobs:

  # Collect all relative paths containing a 'snap/snapcraft.yaml'
  collect_snap_names:
    runs-on: ubuntu-latest
    outputs:
      snap-names: ${{ steps.snap-names.outputs.snap-names }}
    steps:
      - uses: actions/checkout@v3
      - id: snap-names
        run: echo "snap-names=$(find . -type f -name 'snapcraft.yaml' | sed -r 's|^\./([^/]+)/snap/snapcraft.yaml|\1|' | sed 's/-snap$//' | sort | uniq | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  # Run snapcraft for each example
  build_snaps:
    needs: collect_snap_names
    strategy:
      fail-fast: false
      matrix:
        snap-name: ${{ fromJson(needs.collect_snap_names.outputs.snap-names) }}
    name: "Snap ${{ matrix.snap-name }}"
    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@F_add_option_to_select_snap_path
    with:
      branch-name: feature/multi-snap
      snap-name: ${{ matrix.snap-name }}
      snapcraft-build-path: ./${{ matrix.snap-name }}-snap
      snap-install-args: --dangerous
      snapcraft-args: --enable-experimental-extensions

  test_snaps:
    runs-on: ubuntu-20.04
    needs: build_snaps
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: .
      - name: test-script
        run: |
            #!/bin/bash
            set -x

            # Iterate through each file in the folder
            for dir in */; do
                cd "$dir" || exit
                for file in *; do
                    # Check if it is a regular file
                    if [ -f "$file" ]; then
                        sudo snap install "$file" --devmode
                    fi
                done
                cd ..
            done

            sudo snap connect turtlebot3c-bringup:ros-noetic ros-noetic-robot
            sudo snap connect turtlebot3c-nav:ros-noetic ros-noetic-robot
            sudo snap connect turtlebot3c-teleop:ros-noetic ros-noetic-robot

            ## Install ROS
            sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

            sudo apt install curl
            curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
            sudo apt update
            sudo apt install -q ros-noetic-desktop-full
            sudo apt install -q ros-noetic-turtlebot3-gazebo

            source /opt/ros/noetic/setup.sh

            ## set gui arg to false
            #sudo sed -i "s/\(<arg name=\"gui\" value=\"\).*\(\"\/>\)/\1false\2/" /opt/ros/noetic/share/turtlebot3_gazebo/launch/turtlebot3_empty_world.launch
            ## Launch turtlebot simulation

            #echo "launching gazebo sim"
            #TURTLEBOT3_MODEL=waffle_pi roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch debug:=true &
            roscore &
            pid=$!

            sudo snap set turtlebot3c-bringup simulation=true
            sudo snap start turtlebot3c-nav.mapping
            sudo snap start turtlebot3c-nav.navigation

            sleep 5

            check_existence() {
                local topic_or_node=$1
                local name=$2
                local timeout=$3
                local start_time=$(date +%s)
                while true; do
                    $topic_or_node list | grep -q "/$name"
                    if [ $? -eq 0 ]; then
                        echo "$name is running."
                        return 0
                    fi
                    local current_time=$(date +%s)
                    local elapsed_time=$((current_time - start_time))
                    if [ $elapsed_time -ge $timeout ]; then
                        echo "Error $name is not running."
                        sudo snap stop turtlebot3c-bringup
                        exit 1
                    fi
                    sleep 1
                done
            }

            ## test core robot_state_publisher
            check_existence rosnode robot_state_publisher 30

            ## test mapping node
            check_existence rosnode turtlebot3_slam_gmapping 30
            check_existence rostopic map 30

            ## test navigation node
            check_existence rostopic nav_vel 30

            kill $pid
            sudo snap stop turtlebot3c-bringup
