name: snap
on:
  push:
    branches:
      - noetic-devel
  pull_request:
    branches:
      - noetic-devel
  workflow_dispatch:
  workflow_call:
   inputs:
      branch-name:
        required: false
        type: string
        default: ''

jobs:
  snap:
    strategy:
      fail-fast: false
      matrix:
        runner: ['["ubuntu-latest"]', '["ARM64", "self-hosted", "linux", "large", "noble"]']
    uses: canonical/robotics-actions-workflows/.github/workflows/snap-lxc.yaml@main
    secrets:
      store-login: ${{ secrets.STORE_LOGIN }}
    with:
      ubuntu-image: ${{ matrix.runner }}
      lxc-image: "ubuntu:20.04"
      branch-name: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
      snap-name: turtlebot3c
      publish: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      test-script: |
                    #!/bin/bash

                    check_publishing() {
                        local name=$1
                        local timeout=$2
                        local start_time=$(date +%s)

                        function is_publishing() {
                          local name=$1
                          rostopic echo /$name -n 10 > /dev/null 2>&1
                          return $?
                        }

                        while true; do
                            if is_publishing ${name} ; then
                                echo "Topic /$name is publishing data. Exiting."
                                return 0
                            fi

                            local current_time=$(date +%s)
                            local elapsed_time=$((current_time - start_time))

                            if [ $elapsed_time -ge $timeout ]; then
                                echo "Error $name is not publishing."
                                exit 1
                            fi
                            sleep 1
                        done
                    }

                    check_existence() {
                        local topic_or_node=$1
                        local name=$2
                        local timeout=$3
                        local start_time=$(date +%s)

                        function is_running {
                          local topic_or_node="${1}"
                          local name="${2}"
                          ($topic_or_node list | grep -q "/$name")
                          return $?
                        }

                        while true; do
                            if is_running "${topic_or_node}" "${name}" ; then
                                echo "$name is running."
                                return 0
                            fi

                            local current_time=$(date +%s)
                            local elapsed_time=$((current_time - start_time))

                            if [ $elapsed_time -ge $timeout ]; then
                                echo "Error $name is not running."
                                sudo snap stop turtlebot3c
                                exit 1
                            fi
                            sleep 1
                        done
                    }

                    ## Install ROS
                    sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

                    sudo apt install --yes curl
                    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
                    sudo apt update
                    sudo apt install --yes ros-noetic-desktop-full
                    sudo apt install --yes ros-noetic-turtlebot3-gazebo

                    source /opt/ros/noetic/setup.sh

                    echo "Set the simulation parameter"
                    sudo snap set turtlebot3c simulation=true
                    sleep 10

                    ## set gui arg to false with sed since the arg is not exposed
                    sudo sed -i "s/\(<arg name=\"gui\" value=\"\).*\(\"\/>\)/\1false\2/" /opt/ros/noetic/share/turtlebot3_gazebo/launch/turtlebot3_empty_world.launch

                    ## Launch turtlebot simulation

                    TURTLEBOT3_MODEL=waffle_pi roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch &
                    pid=$!

                    echo "check simulation is running"
                    check_publishing scan 30
                    check_publishing joint_states 30

                    ## test core robot_state_publisher
                    check_existence rostopic tf 30
                    check_existence rosnode robot_state_publisher 300

                    ## test mapping node
                    sudo snap start turtlebot3c.mapping
                    check_existence rosnode turtlebot3_slam_gmapping 300
                    check_existence rostopic map 30
                    echo "moving the robot"
                    timeout 5s rostopic pub -r 10 /cmd_vel geometry_msgs/Twist -- '[0.0, 0.0, 0.0]' '[1.0, 0.0, 0.0]' || true
                    check_publishing map 30
                    sudo snap stop turtlebot3c.mapping
                    
                    ## check map has been created
                    timeout=300
                    start_time=$(date +%s)
                    while true; do
                        echo "check map exists.."
                        sudo bash -c 'cd /root/snap/turtlebot3c/common/map/ && ls | grep -q "current_map.yaml"'
                        if [ $? -eq 0 ]; then
                          echo "map found - starting navigation"
                          break
                        fi
                        current_time=$(date +%s)
                        elapsed_time=$((current_time - start_time))
                        if [ $elapsed_time -ge $timeout ]; then
                            echo "Map not found"
                            exit 1
                        fi
                        sleep 1
                    done

                    ## test navigation node
                    sudo snap start turtlebot3c.navigation
                    check_existence rosnode move_base 300
                    check_existence rostopic nav_vel 30
                    sudo snap stop turtlebot3c.navigation

                    kill $pid
                    sudo snap stop turtlebot3c
