name: test turtlebot multi snap

on:
  push:
    tags:
      - 'feature/multi-snap-humble/*'
    branches:
      - feature/multi-snap-humble
  pull_request:
    branches:
      - feature/multi-snap-humble
  workflow_dispatch:
  workflow_call:
   inputs:
      branch-name:
        required: false
        type: string
        default: ''

jobs:
  snaps:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "medium", "noble"]]'
      snapcraft-source-subdir: "turtlebot3c-bringup-snap"
      git-ref: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
      snapcraft-enable-experimental-extensions: true
      snap-track: humble

