name: snap
on:
  push:
    tags:
      - '*'
    branches:
      - main
      - fix/tb3_prague
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - amd64
        - arm64
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        git config --global --add safe.directory /data
    - uses: docker/setup-qemu-action@v1
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      with:
        architecture: ${{ matrix.platform }}
    - uses: actions/upload-artifact@v3
      with:
        name: tb3_snap_upload
        path: ./*.snap

