name: snap
on:
  push:
    branches:
      - feature/multi-snap-jazzy
  pull_request:
    branches:
      - feature/multi-snap-jazzy
  workflow_dispatch:
  workflow_call:
   inputs:
      branch-name:
        required: false
        type: string
        default: ''

jobs:
  snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/snap.yaml@main
    secrets:
      store-login: ${{ secrets.STORE_LOGIN }}
    with:
      ubuntu-image: ubuntu-24.04
      branch-name: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
      snapcraft-build-path: ./turtlebot3c-bringup-snap
      enable-experimental-extensions-env: true
      snap-name: turtlebot3c-bringup
      publish: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      publish-track: jazzy
