name: snap
on:
  push:
    branches:
      - giuseppe/turtlebot-bringup-humble-devel
  pull_request:
    branches:
      - giuseppe/turtlebot-bringup-humble-devel
  workflow_dispatch:
  workflow_call:
   inputs:
      branch-name:
        required: false
        type: string
        default: ''

jobs:
  snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/snap.yaml@main
    secrets:
      store-login: ${{ secrets.STORE_LOGIN }}
    with:
      ubuntu-image: ubuntu-22.04
      branch-name: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
      snapcraft-build-path: ./turtlebot3c-bringup-snap
      snapcraft-args: --enable-experimental-extensions
      snap-name: turtlebot3c-bringup
      publish: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      test-script: |
                    #!/bin/bash
                    sudo snap install ros2-cli --channel=humble/beta

                    check_node() {
                        local node_name=$1
                        ros2-cli.ros2 node list | grep -q "/$node_name"
                        if [ $? -eq 0 ]; then
                            echo "$node_name is running."
                        else
                            echo "Error - $node_name is not running."
                            kill $pid
                            exit 1
                        fi
                    }
                    sudo snap set turtlebot3c-bringup simulation=true
                    check_node robot_state_publisher
