name: test turtlebot multi snap

on:
  push:
    branches:
      - feature/multi-snap
  pull_request:
    branches:
      - feature/multi-snap
  workflow_dispatch:
  workflow_call:

jobs:

  # Collect all relative paths containing a 'snap/snapcraft.yaml'
  collect_snap_names:
    runs-on: ubuntu-latest
    outputs:
      snap-names: ${{ steps.snap-names.outputs.snap-names }}
    steps:
      - uses: actions/checkout@v3
      - id: snap-names
        run: echo "snap-names=$(find . -type f -name 'snapcraft.yaml' | sed -r 's|^\./([^/]+)/snap/snapcraft.yaml|\1|' | sed 's/-snap$//' | sort | uniq | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  # Run snapcraft for each example
  run_tests:
    needs: collect_snap_names
    strategy:
      fail-fast: false
      matrix:
        snap-name: ${{ fromJson(needs.collect_snap_names.outputs.snap-names) }}
    name: "Snap ${{ matrix.snap-name }}"
    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@F_add_option_to_select_snap_path
    with:
      branch-name: feature/multi-snap-add-CI-tests
      snap-name: ${{ matrix.snap-name }}
      snapcraft-build-path: ./${{ matrix.snap-name }}-snap
      snap-install-args: --dangerous
      snapcraft-args: --enable-experimental-extensions
