#!/bin/sh -e

# set default configuration values
snapctl set simulation=false

# set default lidar model for real robot
snapctl set lds-model=LDS-01

# set default turtlebot 3 model
snapctl set turtlebot3-model=waffle_pi

# set default ROS master hostname
snapctl set ros-master-host=$(hostname).local

# set default OpenCR firmware auto update
snapctl set opencr-auto-update=false

