#!/bin/sh -e

# set default configuration values
snapctl set simulation=false

# set default turtlebot 3 model
snapctl set turtlebot3-model=waffle_pi

# set default ROS master hostname
snapctl set ros-master-host=$(hostname).local

